export interface Rule {
  code: string;
  rpm: string;
  sound: string;
  vibration: string;
  temperature: string;
  result: string;
}

export const rules: Rule[] = [
  { code: "D001", rpm: "&&", sound: "&&", vibration: "&&", temperature: "&&", result: "Lolos QC" },
  { code: "D002", rpm: "&&", sound: "&&", vibration: "&&", temperature: "<", result: "Lolos QC" },
  { code: "D003", rpm: "&&", sound: "&&", vibration: "&&", temperature: ">", result: "Cek Pendinginan" },
  { code: "D004", rpm: "&&", sound: "&&", vibration: "<", temperature: "&&", result: "Lolos QC" },
  { code: "D005", rpm: "&&", sound: "&&", vibration: "<", temperature: "<", result: "Lolos QC" },
  { code: "D006", rpm: "&&", sound: "&&", vibration: "<", temperature: ">", result: "Cek Pendinginan" },
  { code: "D007", rpm: "&&", sound: "&&", vibration: ">", temperature: "&&", result: "Cek Bearing" },
  { code: "D008", rpm: "&&", sound: "&&", vibration: ">", temperature: "<", result: "Cek Bearing" },
  { code: "D009", rpm: "&&", sound: "&&", vibration: ">", temperature: ">", result: "Cek Bearing + Pendinginan" },
  { code: "D010", rpm: "&&", sound: "<", vibration: "&&", temperature: "&&", result: "Lolos QC" },
  { code: "D011", rpm: "&&", sound: "<", vibration: "&&", temperature: "<", result: "Lolos QC" },
  { code: "D012", rpm: "&&", sound: "<", vibration: "&&", temperature: ">", result: "Cek Pendinginan" },
  { code: "D013", rpm: "&&", sound: "<", vibration: "<", temperature: "&&", result: "Lolos QC" },
  { code: "D014", rpm: "&&", sound: "<", vibration: "<", temperature: "<", result: "Lolos QC" },
  { code: "D015", rpm: "&&", sound: "<", vibration: "<", temperature: ">", result: "Cek Pendinginan" },
  { code: "D016", rpm: "&&", sound: "<", vibration: ">", temperature: "&&", result: "Cek Bearing" },
  { code: "D017", rpm: "&&", sound: "<", vibration: ">", temperature: "<", result: "Cek Bearing" },
  { code: "D018", rpm: "&&", sound: "<", vibration: ">", temperature: ">", result: "Cek Bearing + Pendinginan" },
  { code: "D019", rpm: "&&", sound: ">", vibration: "&&", temperature: "&&", result: "Cek Noise" },
  { code: "D020", rpm: "&&", sound: ">", vibration: "&&", temperature: "<", result: "Cek Noise" },
  { code: "D021", rpm: "&&", sound: ">", vibration: "&&", temperature: ">", result: "Cek Noise + Pendinginan" },
  { code: "D022", rpm: "&&", sound: ">", vibration: "<", temperature: "&&", result: "Cek Noise" },
  { code: "D023", rpm: "&&", sound: ">", vibration: "<", temperature: "<", result: "Cek Noise" },
  { code: "D024", rpm: "&&", sound: ">", vibration: "<", temperature: ">", result: "Cek Noise + Pendinginan" },
  { code: "D025", rpm: "&&", sound: ">", vibration: ">", temperature: "&&", result: "Cek Noise + Bearing" },
  { code: "D026", rpm: "&&", sound: ">", vibration: ">", temperature: "<", result: "Cek Noise + Bearing" },
  { code: "D027", rpm: "&&", sound: ">", vibration: ">", temperature: ">", result: "Cek Noise + Bearing + Pendinginan" },
  { code: "D028", rpm: "<", sound: "&&", vibration: "&&", temperature: "&&", result: "Cek RPM" },
  { code: "D029", rpm: "<", sound: "&&", vibration: "&&", temperature: "<", result: "Cek RPM" },
  { code: "D030", rpm: "<", sound: "&&", vibration: "&&", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D031", rpm: "<", sound: "&&", vibration: "<", temperature: "&&", result: "Cek RPM" },
  { code: "D032", rpm: "<", sound: "&&", vibration: "<", temperature: "<", result: "Cek RPM" },
  { code: "D033", rpm: "<", sound: "&&", vibration: "<", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D034", rpm: "<", sound: "&&", vibration: ">", temperature: "&&", result: "Cek RPM + Bearing" },
  { code: "D035", rpm: "<", sound: "&&", vibration: ">", temperature: "<", result: "Cek RPM + Bearing" },
  { code: "D036", rpm: "<", sound: "&&", vibration: ">", temperature: ">", result: "Cek RPM + Bearing + Pendinginan" },
  { code: "D037", rpm: "<", sound: "<", vibration: "&&", temperature: "&&", result: "Cek RPM" },
  { code: "D038", rpm: "<", sound: "<", vibration: "&&", temperature: "<", result: "Cek RPM" },
  { code: "D039", rpm: "<", sound: "<", vibration: "&&", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D040", rpm: "<", sound: "<", vibration: "<", temperature: "&&", result: "Cek RPM" },
  { code: "D041", rpm: "<", sound: "<", vibration: "<", temperature: "<", result: "Cek RPM" },
  { code: "D042", rpm: "<", sound: "<", vibration: "<", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D043", rpm: "<", sound: "<", vibration: ">", temperature: "&&", result: "Cek RPM + Bearing" },
  { code: "D044", rpm: "<", sound: "<", vibration: ">", temperature: "<", result: "Cek RPM + Bearing" },
  { code: "D045", rpm: "<", sound: "<", vibration: ">", temperature: ">", result: "Cek RPM + Bearing + Pendinginan" },
  { code: "D046", rpm: "<", sound: ">", vibration: "&&", temperature: "&&", result: "Cek RPM + Noise" },
  { code: "D047", rpm: "<", sound: ">", vibration: "&&", temperature: "<", result: "Cek RPM + Noise" },
  { code: "D048", rpm: "<", sound: ">", vibration: "&&", temperature: ">", result: "Cek RPM + Noise + Pendinginan" },
  { code: "D049", rpm: "<", sound: ">", vibration: "<", temperature: "&&", result: "Cek RPM + Noise" },
  { code: "D050", rpm: "<", sound: ">", vibration: "<", temperature: "<", result: "Cek RPM + Noise" },
  { code: "D051", rpm: "<", sound: ">", vibration: "<", temperature: ">", result: "Cek RPM + Noise + Pendinginan" },
  { code: "D052", rpm: "<", sound: ">", vibration: ">", temperature: "&&", result: "Cek RPM + Noise + Bearing" },
  { code: "D053", rpm: "<", sound: ">", vibration: ">", temperature: "<", result: "Cek RPM + Noise + Bearing" },
  { code: "D054", rpm: "<", sound: ">", vibration: ">", temperature: ">", result: "Cek RPM + Noise + Bearing + Pendinginan" },
  { code: "D055", rpm: ">", sound: "&&", vibration: "&&", temperature: "&&", result: "Cek RPM" },
  { code: "D056", rpm: ">", sound: "&&", vibration: "&&", temperature: "<", result: "Cek RPM" },
  { code: "D057", rpm: ">", sound: "&&", vibration: "&&", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D058", rpm: ">", sound: "&&", vibration: "<", temperature: "&&", result: "Cek RPM" },
  { code: "D059", rpm: ">", sound: "&&", vibration: "<", temperature: "<", result: "Cek RPM" },
  { code: "D060", rpm: ">", sound: "&&", vibration: "<", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D061", rpm: ">", sound: "&&", vibration: ">", temperature: "&&", result: "Cek RPM + Bearing" },
  { code: "D062", rpm: ">", sound: "&&", vibration: ">", temperature: "<", result: "Cek RPM + Bearing" },
  { code: "D063", rpm: ">", sound: "&&", vibration: ">", temperature: ">", result: "Cek RPM + Bearing + Pendinginan" },
  { code: "D064", rpm: ">", sound: "<", vibration: "&&", temperature: "&&", result: "Cek RPM" },
  { code: "D065", rpm: ">", sound: "<", vibration: "&&", temperature: "<", result: "Cek RPM" },
  { code: "D066", rpm: ">", sound: "<", vibration: "&&", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D067", rpm: ">", sound: "<", vibration: "<", temperature: "&&", result: "Cek RPM" },
  { code: "D068", rpm: ">", sound: "<", vibration: "<", temperature: "<", result: "Cek RPM" },
  { code: "D069", rpm: ">", sound: "<", vibration: "<", temperature: ">", result: "Cek RPM + Pendinginan" },
  { code: "D070", rpm: ">", sound: "<", vibration: ">", temperature: "&&", result: "Cek RPM + Bearing" },
  { code: "D071", rpm: ">", sound: "<", vibration: ">", temperature: "<", result: "Cek RPM + Bearing" },
  { code: "D072", rpm: ">", sound: "<", vibration: ">", temperature: ">", result: "Cek RPM + Bearing + Pendinginan" },
  { code: "D073", rpm: ">", sound: ">", vibration: "&&", temperature: "&&", result: "Cek RPM + Noise" },
  { code: "D074", rpm: ">", sound: ">", vibration: "&&", temperature: "<", result: "Cek RPM + Noise" },
  { code: "D075", rpm: ">", sound: ">", vibration: "&&", temperature: ">", result: "Cek RPM + Noise + Pendinginan" },
  { code: "D076", rpm: ">", sound: ">", vibration: "<", temperature: "&&", result: "Cek RPM + Noise" },
  { code: "D077", rpm: ">", sound: ">", vibration: "<", temperature: "<", result: "Cek RPM + Noise" },
  { code: "D078", rpm: ">", sound: ">", vibration: "<", temperature: ">", result: "Cek RPM + Noise + Pendinginan" },
  { code: "D079", rpm: ">", sound: ">", vibration: ">", temperature: "&&", result: "Cek RPM + Noise + Bearing" },
  { code: "D080", rpm: ">", sound: ">", vibration: ">", temperature: "<", result: "Cek RPM + Noise + Bearing" },
  { code: "D081", rpm: ">", sound: ">", vibration: ">", temperature: ">", result: "Cek RPM + Noise + Bearing + Pendinginan" }
];
